apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include .Values.service.annotations | toYaml | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports: {{- include .Values.service.ports | toYaml | indent 4 }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (.Values.service.loadbalancerIP) (eq .Values.service.type "LoadBalancer") }}
  loadbalancerIP: {{ .Values.service.loadbalancerIP }}
  {{- end }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{ include .Values.service.sessionAffinityConfig | toYaml | indent 4 }}
  {{- end }}
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
