---
name: "Push Action"
on: [push]
jobs:
  My-First-GitAction-Job:
    runs-on: self-hosted
    steps:
      - run: echo "wow such test"
      - run: echo "much test"
      - run: echo "much wow"
      - name: checkout
        uses: actions/checkout@main
      - run: |
          ls -la {{ github.workspace }}
          echo "wow!"
      - run: echo "ğŸ• ğŸ’•"